// Mocks generated by Mockito 5.4.6 from annotations
// in neocalculator/test/calculator_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:get/get.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:neocalculator/controllers/preference_controller.dart' as _i6;
import 'package:neocalculator/repo/database.dart' as _i4;
import 'package:neocalculator/utils/result_model.dart' as _i7;
import 'package:neocalculator/utils/settings_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsModel_0 extends _i1.SmartFake implements _i2.SettingsModel {
  _FakeSettingsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseRepository extends _i1.Mock
    implements _i4.DatabaseRepository {
  MockDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> set<T>(String? key, T? value) =>
      (super.noSuchMethod(
            Invocation.method(#set, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  T? get<T>(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as T?);

  @override
  _i5.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [PreferencesController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesController extends _i1.Mock
    implements _i6.PreferencesController {
  MockPreferencesController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsModel get settingsModel =>
      (super.noSuchMethod(
            Invocation.getter(#settingsModel),
            returnValue: _FakeSettingsModel_0(
              this,
              Invocation.getter(#settingsModel),
            ),
          )
          as _i2.SettingsModel);

  @override
  List<_i7.ResultModel> get results =>
      (super.noSuchMethod(
            Invocation.getter(#results),
            returnValue: <_i7.ResultModel>[],
          )
          as List<_i7.ResultModel>);

  @override
  bool get isFirstRun =>
      (super.noSuchMethod(Invocation.getter(#isFirstRun), returnValue: false)
          as bool);

  @override
  bool get isFirstCall =>
      (super.noSuchMethod(Invocation.getter(#isFirstCall), returnValue: false)
          as bool);

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateSettings(_i2.SettingsModel? settingsModel) => super.noSuchMethod(
    Invocation.method(#updateSettings, [settingsModel]),
    returnValueForMissingStub: null,
  );

  @override
  void saveResult(_i7.ResultModel? result) => super.noSuchMethod(
    Invocation.method(#saveResult, [result]),
    returnValueForMissingStub: null,
  );

  @override
  void clearResults() => super.noSuchMethod(
    Invocation.method(#clearResults, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
